language: python
env:
  - "DJANGO_VERSION='>=1.7,<1.8'"
  - "DJANGO_VERSION='>=1.8,<1.9'"
  - "DJANGO_VERSION='>=1.9,<1.10'"
  - "DJANGO_VERSION=''"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  exclude:
    - python: "3.3"
      env: "DJANGO_VERSION='>=1.9,<1.10'"
    - python: "3.3"
      env: "DJANGO_VERSION=''"
    - python: "3.5"
      env: "DJANGO_VERSION='>=1.7,<1.8'"
# command to install dependencies
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install djangorestframework"
# command to run tests
script:
  - "python setup.py test"
