language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install Django"
  - "pip install djangorestframework"
# command to run tests
script:
  - "python setup.py test"
