language: python
env:
  - "DJANGO_VERSION='>=1.10,<1.11'"
  - "DJANGO_VERSION='>=1.11,<1.12'"
  - "DJANGO_VERSION='>=2.0,<2.1'"
  - "DJANGO_VERSION=''"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
exclude:
  - python: "2.7"
    env: "DJANGO_VERSION='>=2.0,<2.1'"
  - python: "2.7"
    env: "DJANGO_VERSION=''"
# command to install dependencies
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -r requirements.txt"
# command to run tests
script:
  - "python setup.py test"
