language: python
env:
  - "DJANGO_VERSION='>=1.6,<1.7'"
  - "DJANGO_VERSION='>=1.7,<1.8'"
  - "DJANGO_VERSION=''"
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install djangorestframework"
# command to run tests
script:
  - "python setup.py test"
